name: BUILDING VENDOR (AOSP SOURCES STUCK)

on:
  push:
    branches: [ main ]
    paths:
    - 'cleanup.sh'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@main
      - name: Cleanups
        uses: rokibhasansagar/slimhub_actions@main
      - name: Apt Checks
        run: sudo apt list --installed
      - name: Local Bin checks
        run: ls -lAog /usr/local/bin
      - name: Glbal Bin checks
        run: ls -lAog /usr/bin
      - name: Envirnment Variables Check
        run: printenv | sort
      - name: environment setup
        run: |
             sudo add-apt-repository ppa:openjdk-r/ppa
             sudo apt-get update
             sudo apt-get install bison build-essential curl ccache flex lib32ncurses5-dev lib32z1-dev libesd0-dev libncurses5-dev libsdl1.2-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev git-core make phablet-tools gperf openjdk-8-jdk -y
           
             
                        
       
             
            
              
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
