name: slimhub_actions Check on Ubuntu

on:
  push:
    branches: [ main ]
    paths:
    - 'cleanup.sh'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@main
      - name: Cleanups
        uses: rokibhasansagar/slimhub_actions@main
      - name: Apt Checks
        run: sudo apt list --installed
      - name: Local Bin checks
        run: ls -lAog /usr/local/bin
      - name: Glbal Bin checks
        run: ls -lAog /usr/bin
      - name: Envirnment Variables Check
        run: printenv | sort
