name: BUILDING VENDOR (AOSP SOURCES STUCK)

on:
  push:
    branches: [ main ]
    paths:
    - 'cleanup.sh'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@main
      - name: Cleanups
        uses: rokibhasansagar/slimhub_actions@main
      - name: Apt Checks
        run: sudo apt list --installed
      - name: Local Bin checks
        run: ls -lAog /usr/local/bin
      - name: Glbal Bin checks
        run: ls -lAog /usr/bin
      - name: Envirnment Variables Check
        run: printenv | sort
        
        
       
 
                   run: |
                        sudo add-apt-repository ppa:openjdk-r/ppa
                        sudo apt-get update
                        sudo apt-get install bison build-essential curl ccache flex lib32ncurses5-dev lib32z1-dev libesd0-dev libncurses5-dev libsdl1.2-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev git-core make phablet-tools gperf openjdk-8-jdk -y
                        mkdir ~/bin
                        PATH=~/bin:$PATH
                        cd ~/bin
                        curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
                        chmod a+x ~/bin/repo
                        git clone https://github.com/akhilnarang/scripts.git scripts
                        cd scripts
                        bash setup/android_build_env.sh
                        sudo add-apt-repository ppa:deadsnakes/ppa
                        sudo apt-get update
                        sudo apt-get install python3.6
                        sudo apt-get install python3.7
                        sudo apt install python3-pip
                        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
                        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
            
            name: Sync aosp sources 
                  run: |
                       mkdir aosp
                       cd aosp
                       git config --global user.name aks-max
                       git config --global user.email kasambrar04@gmail.com
                       repo init -u https://android.googlesource.com/platform/manifest -b master
                      repo sync
              
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
